on:
  push:
    branches:
      - main
    paths-ignore:
      - .vscode/**
      - .workspace/**
      - '**.md'
      - .env.development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build

      - name: Archive Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: Archive Apps
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: Publish Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Download Apps
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy Apps
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
