on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .vscode/**
      - .workspace/**
      - '**.md'
      - .env.development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Unit Test
        run: yarn test:ut

      - name: Build
        run: yarn build

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: ./build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: archive
          path: ./build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
